config:
  bt_merchant_id: "merchant_id from Braintree API Keys"
  bt_env: "Sandbox OR Production"
  slack_url: "configured with slack"
  slack_channel: "username or channel"
  slack_username: "Braintree"
  slack_emoji: ":money_with_wings:"
